### ISSUE TITLE
`parseHelper` and other test helpers that use it can cause non-deterministic test failures

### ISSUE THREAD

**Issue by lars-reimann** [eclipse-langium/langium#1146]
If no URI is provided to the `parseHelper` function, it [generates one](https://github.com/langium/langium/blob/13f482bf33169092f17cf92e327b799c21f5b4dc/packages/langium/src/test/langium-test.ts#L29) using a random number and the first registered file extension of the DSL. With many tests, however, collisions become increasingly noticeable, causing some tests to fail non-deterministically with the following error:

```txt
Error: A document with the URI 'file:///6821462.sdspipe' is already present.
    at DefaultLangiumDocuments.addDocument (...\node_modules\langium\src\workspace\documents.ts:328:19)
    at ...\node_modules\langium\src\test\langium-test.ts:33:52
    at parseDocument (...\node_modules\langium\src\test\langium-test.ts:356:52)
    at ...\node_modules\langium\src\test\langium-test.ts:336:32
    at ...\tests\formatting\testFormatter.test.ts:15:40
    at file://.../node_modules/@vitest/runner/dist/index.js:357:140
    at file://.../node_modules/@vitest/runner/dist/index.js:242:72
    at file:///.../node_modules/@vitest/runner/dist/index.js:41:26
    at runTest (file:///.../node_modules/@vitest/runner/dist/index.js:599:17)
    at runSuite (file:///.../node_modules/@vitest/runner/dist/index.js:708:15)
```

There are $10^7$ possibilities for the random number, so at 100 tests the probability of any collision is 0.05%, at 200 tests 0.2%, at 500 tests 1.24%, and at 1000 tests already 4.87%.

While this can be mitigated by specifying a URI when using `parseHelper` directly, other functions like `validationHelper` or `expectFormatting` call `parseHelper` internally but do not allow specifying the URI manually.

Langium version: 1.2.1
Package name: `langium`

## Steps To Reproduce

Since the bug is non-deterministic, I cannot provide exact steps for reproduction. But I reckon the description above suffices.

## The current behavior

More tests increase the probability of collisions to levels that are no longer tolerable.

## The expected behavior

Even with many tests, the generated URIs should not collide. Maybe UUIDs could be used instead of the random numbers.

**Comment by lars-reimann** [comment]
> Hm, it make might sense to just use a continuous id for the tests (or uuid). In any case, you can also just call `clearDocuments` on the services in between tests to clear the documents list.

That's a nice workaround as well, thanks.
